version: '3.8'

services:
  book-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - COUNTER_SERVICE_URL=http://counter-api:3001
    depends_on:
      - counter-api
    networks:
      - library-network
    volumes:
      - ./public/uploads:/app/public/uploads

  counter-api:
    build: ./counter-api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATA_DIR=/app/data
    volumes:
      - ./counter-api/data:/app/data
    networks:
      - library-network

networks:
  library-network:
    driver: bridge